[package]
name = "dgbir"
version = "0.1.0"
edition = "2021"

[features]
default = ["asm_debug"]
asm_debug = []

[dependencies]
capstone = "0.13.0"
dynasmrt = "3.2.1"
itertools = "0.14.0"
nom = "8.0.0"
nom-language = "0.1.0"
ordered-float = "5.0.0"
